// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Ident-2]
	_ = x[Int-3]
	_ = x[Assign-4]
	_ = x[Plus-5]
	_ = x[Minus-6]
	_ = x[Bang-7]
	_ = x[Asterisk-8]
	_ = x[Slash-9]
	_ = x[Lt-10]
	_ = x[Gt-11]
	_ = x[Eq-12]
	_ = x[Ne-13]
	_ = x[Comma-14]
	_ = x[Semicolon-15]
	_ = x[LeftParen-16]
	_ = x[RightParen-17]
	_ = x[LeftBrace-18]
	_ = x[RightBrace-19]
	_ = x[Function-20]
	_ = x[Let-21]
	_ = x[True-22]
	_ = x[False-23]
	_ = x[If-24]
	_ = x[Else-25]
	_ = x[Return-26]
}

const _Type_name = "IllegalEOFIdentIntAssignPlusMinusBangAsteriskSlashLtGtEqNeCommaSemicolonLeftParenRightParenLeftBraceRightBraceFunctionLetTrueFalseIfElseReturn"

var _Type_index = [...]uint8{0, 7, 10, 15, 18, 24, 28, 33, 37, 45, 50, 52, 54, 56, 58, 63, 72, 81, 91, 100, 110, 118, 121, 125, 130, 132, 136, 142}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
