// Code generated by devtools/genhelpdoc.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

const helpDoc = `
Starbuck is a HTTP server that runs on https://exp.astrophena.name.
`

func init() { cli.SetDescription(helpDoc) }
