// Code generated by devtools/gencredits.go; DO NOT EDIT.

package main

const credits = `kp utilizes the following third-party libraries:

- github.com/tobischo/argon2: BSD-3-Clause
- github.com/tobischo/gokeepasslib/v3: MIT
- golang.org/x/crypto: BSD-3-Clause
- golang.org/x/sys: BSD-3-Clause
- golang.org/x/term: BSD-3-Clause
`
