// © 2024 Ilya Mateyko. All rights reserved.
// Use of this source code is governed by the ISC
// license that can be found in the LICENSE.md file.

// Code generated by devtools/gen/helpdoc.go; DO NOT EDIT.

package main

const helpDoc = `
Kp reads passwords from KeePass databases.
`
