// Code generated by gendocs.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

const helpDoc = `
goupdate checks the Go version specified in the go.mod file of a Go project,
updates it to the latest Go version if it is outdated, and creates a GitHub pull
request with the updated go.mod file.
`

func init() { cli.SetDescription(helpDoc) }
