//go:build ignore

// genhelpdoc.go generates help documentation for all commands from their doc comments.

package main

import (
	"bytes"
	"go/build"
	"go/format"
	"io/fs"
	"log"
	"os"
	"os/exec"
	"path/filepath"
)

func main() {
	if err := filepath.WalkDir("./cmd", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if !d.IsDir() {
			return nil
		}

		pkg, err := build.ImportDir(path, build.IgnoreVendor)
		if err != nil || len(pkg.GoFiles) == 0 {
			return nil
		}

		out, err := exec.Command("go", "doc", path).Output()
		if err != nil {
			return err
		}

		var buf bytes.Buffer
		buf.WriteString("// Code generated by devtools/genhelpdoc.go; DO NOT EDIT.\n\n")
		buf.WriteString("package main\n\n")
		buf.WriteString("import \"go.astrophena.name/tools/internal/cli\"\n\n")
		buf.WriteString("const helpDoc = `\n")
		buf.Write(out)
		buf.WriteString("`\n\n")
		buf.WriteString("func init() { cli.SetDescription(helpDoc) }\n")

		src, err := format.Source(buf.Bytes())
		if err != nil {
			return err
		}

		return os.WriteFile(filepath.Join(path, "helpdoc.go"), src, 0o644)
	}); err != nil {
		log.Fatal(err)
	}
}
