#!/bin/sh

# genreadme.sh generates README.md from the documentation of the tools.

cd "$(dirname $0)/.."

template='- {{ .Doc }}'

echo "<!-- Generated by devtools/genreadme.sh; DO NOT EDIT. -->\n" >README.md
echo "This repository holds personal tools:\n" >>README.md
go list -f "$template" ./cmd/... >>README.md
cat <<'EOF' >>README.md

Install them:

```sh
go install go.astrophena.name/tools/cmd/...@master
```
EOF
