//go:build ignore

// genreadme.go generates README.md from the documentation of the tools.

package main

import (
	"bytes"
	"log"
	"os"
	"os/exec"
	"strings"
)

func main() {
	var sb strings.Builder

	sb.WriteString("<!-- Generated by devtools/genreadme.go; DO NOT EDIT. -->\n\n")
	sb.WriteString("This repository holds personal tools:\n\n")

	const template = "- {{ .Doc }}"
	var buf bytes.Buffer
	cmd := exec.Command("go", "list", "-f", template, "./cmd/...")
	cmd.Stdout = &sb
	cmd.Stderr = &buf
	if err := cmd.Run(); err != nil {
		log.Fatalf("'go list' failed with %v:\n%s", err, buf.String())
	}

	sb.WriteString("\nInstall them:\n\n")
	sb.WriteString("```sh\n")
	sb.WriteString("$ go install go.astrophena.name/tools/cmd/...@master\n")
	sb.WriteString("```\n")

	if err := os.WriteFile("README.md", []byte(sb.String()), 0o644); err != nil {
		log.Fatalf("failed to write README.md: %v", err)
	}
}
