// Package docs contains documentation for packages in tools.
package docs

import (
	"embed"
	"io/fs"
	"net/http"
)

//go:generate doc2go -out generated -internal ../../...

// Generated contains documentation for packages in tools as a static HTML site.
// It's generated by doc2go.
//
//go:embed all:generated
var Generated embed.FS

// Handler returns a [http.Handler] that serves docs from [Generated].
func Handler() http.Handler {
	sub, err := fs.Sub(Generated, "generated")
	if err != nil {
		panic(err)
	}
	return http.FileServer(http.FS(sub))
}
