// Code generated by devtools/genhelpdoc.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

const helpDoc = `
Dupfind finds duplicate files in a directory.
`

func init() { cli.SetDescription(helpDoc) }
