// Code generated by gendocs.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

const helpDoc = `
dupfind finds duplicate files in a directory.
`

func init() { cli.SetDescription(helpDoc) }
