// Code generated by gendocs.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

const helpDoc = `
Txtar is a command-line tool for creating and extracting txtar archives.

It can be used in two ways:

To create a txtar archive:

    $ txtar -c <archive> <directory>

This will create a txtar archive named <archive> containing all the files and
directories from the specified <directory>.

To extract a txtar archive:

    $ txtar <archive> <directory>

This will extract the contents of the txtar archive named <archive> into the
specified directory.
`

func init() { cli.SetDescription(helpDoc) }
