// © 2024 Ilya Mateyko. All rights reserved.
// Use of this source code is governed by the ISC
// license that can be found in the LICENSE.md file.

// Code generated by devtools/gen/credits.go; DO NOT EDIT.

package main

const credits = `audiorenamer utilizes the following third-party libraries:

- github.com/dhowden/tag: BSD-2-Clause
`
