// © 2024 Ilya Mateyko. All rights reserved.
// Use of this source code is governed by the ISC
// license that can be found in the LICENSE.md file.

// Code generated by devtools/gen/helpdoc.go; DO NOT EDIT.

package main

const helpDoc = `
Audiorenamer traverses a directory and renames music tracks based on their
metadata using Go's text/template package.

The new filename is generated by executing a Go template against the file's
metadata (see https://pkg.go.dev/github.com/dhowden/tag#Metadata for available
fields). 'track' template function is provided for convenience, returning only
the track number from the metadata.

If the template results in a filename containing slashes, these are removed.
`
