// © 2024 Ilya Mateyko. All rights reserved.
// Use of this source code is governed by the ISC
// license that can be found in the LICENSE.md file.

// Code generated by devtools/gen/info.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

func init() {
	cli.SetInfo(cli.Info{Name: ".", Description: "Audiorenamer traverses a directory and renames music tracks based on their\nmetadata using Go's text/template package.\n\n# Usage\n\n    $ audiorenamer [flags...] <dir>\n\nThe new filename is generated by executing a Go template against the file's\nmetadata (see https://pkg.go.dev/github.com/dhowden/tag#Metadata for available\nfields). 'track' template function is provided for convenience, returning only\nthe track number from the metadata.\n\nIf the template results in a filename containing slashes, these are removed.\n"})
}
