// Code generated by devtools/gencredits.go; DO NOT EDIT.

package main

const credits = `starlet utilizes the following third-party libraries:

- github.com/benbjohnson/hashfs: MIT
- github.com/writeas/go-strip-markdown/v2: MIT
- go.starlark.net: BSD-3-Clause
- golang.org/x/crypto: BSD-3-Clause
- golang.org/x/net: BSD-3-Clause
- golang.org/x/sys: BSD-3-Clause
- golang.org/x/text: BSD-3-Clause
`
