// Code generated by devtools/genhelpdoc.go; DO NOT EDIT.

package main

const helpDoc = `
Starlet allows to create and manage a Telegram bot using the Starlark scripting
language.

Starlet serves an HTTP server to handle Telegram webhook updates and bot
maintenance. The bot's code is sourced from a specified GitHub Gist. Also
Starlet includes features such as user authentication via the Telegram login
widget, ensuring that only the designated bot owner can manage the bot.

When running on Render, Starlet periodically pings itself to prevent Render from
putting it to sleep, ensuring continuous operation.

# Starlark language

See Starlark spec for reference.

Additional modules and functions available from bot code:

  - call: Make HTTP POST requests to the Telegram API, facilitating bot commands
    and interactions.
  - escape_html: Escape HTML string.
  - gemini: Generate text using the Gemini API.
  - json: The Starlark JSON module, enabling JSON parsing and encoding.
  - time: The Starlark time module, providing time-related functions.

[Render]: https://render.com
[Starlark spec]: https://github.com/bazelbuild/starlark/blob/master/spec.md
`
