// Code generated by gendocs.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

const helpDoc = `
starlet implements a Telegram bot written in Starlark language.
`

func init() { cli.SetDescription(helpDoc) }
