// © 2024 Ilya Mateyko. All rights reserved.
// Use of this source code is governed by the ISC
// license that can be found in the LICENSE.md file.

// Code generated by devtools/gencredits.go; DO NOT EDIT.

package main

const credits = `tgfeed utilizes the following third-party libraries:

- github.com/PuerkitoBio/goquery: BSD-3-Clause
- github.com/andybalholm/cascadia: BSD-2-Clause
- github.com/golang-jwt/jwt/v5: MIT
- github.com/json-iterator/go: MIT
- github.com/mmcdole/gofeed: MIT
- github.com/mmcdole/goxpp: MIT
- github.com/modern-go/concurrent: Apache-2.0
- github.com/modern-go/reflect2: Apache-2.0
- go.starlark.net: BSD-3-Clause
- golang.org/x/net: BSD-3-Clause
- golang.org/x/sys: BSD-3-Clause
- golang.org/x/text: BSD-3-Clause
`
