// Code generated by devtools/gencredits.go; DO NOT EDIT.

package main

const credits = `mdserve utilizes the following third-party libraries:

- github.com/benbjohnson/hashfs: MIT
- golang.org/x/crypto: BSD-3-Clause
- golang.org/x/net: BSD-3-Clause
- golang.org/x/text: BSD-3-Clause
- rsc.io/markdown: BSD-3-Clause
`
