// © 2024 Ilya Mateyko. All rights reserved.
// Use of this source code is governed by the ISC
// license that can be found in the LICENSE.md file.

// Code generated by devtools/gen/info.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

func init() {
	cli.SetInfo(cli.Info{Name: ".", Description: "Mdserve serves Markdown files from a directory.\n\n# Usage\n\n    $ mdserve [flags...] [dir]\n"})
}
