// Code generated by devtools/genhelpdoc.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

const helpDoc = `
Cmdtop displays the top of most used commands in bash history.
`

func init() { cli.SetDescription(helpDoc) }
