// Code generated by gendocs.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

const helpDoc = `
renamer renames files sequentially.
`

func init() { cli.SetDescription(helpDoc) }
