// © 2024 Ilya Mateyko. All rights reserved.
// Use of this source code is governed by the ISC
// license that can be found in the LICENSE.md file.

// Code generated by devtools/gen/info.go; DO NOT EDIT.

package main

import "go.astrophena.name/tools/internal/cli"

func init() {
	cli.SetInfo(cli.Info{Name: ".", Description: "Renamer renames files in a specified directory sequentially, starting from a\ngiven number.\n\n# Usage\n\n    $ renamer [flags...] <dir>\n\nIt sorts the files based on name, time, size, or type before renaming. If a file\nwith the new name already exists, it skips the file and continues to the next.\n"})
}
