name: 'Configure SSH credentials'
description: 'Configure SSH credentials in GitHub Actions workflow'
inputs:
  host:
    description: 'Host name to connect.'
    required: true
  port:
    description: 'SSH port to connect.'
    required: true
  key:
    description: 'SSH key to use.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Configure SSH credentials'
      shell: 'bash'
      id: 'configure'
      env:
        HOST: '${{ inputs.host }}'
        PORT: '${{ inputs.port }}'
        KEY: '${{ inputs.key }}'
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts
        echo "$KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keygen -y -f ~/.ssh/id_ed25519 >~/.ssh/id_ed25519.pub
