name: 'Autobump'
on:
  schedule:
    # At 00:00 on day-of-month 1.
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  run:
    name: 'Run'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v4'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go.mod'
      - name: 'Autobump'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          go run devtools/autobump.go
          git push --tags
