name: "Deploy"
on:
  workflow_run:
    workflows: ["Test"]
    branches: ["master"]
    types:
      - "completed"
permissions:
  id-token: "write"
  contents: "read"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out"
        uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" # v6.0.3
        with:
          # Show Git tags in version.
          fetch-depth: 0
      - name: "Set up Go"
        uses: "actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16" # v6.5.0
        with:
          go-version-file: "go.mod"
      - name: "Set up Zig"
        uses: "mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29" # v2.2.1
      - name: "Deploy starlet"
        run: "./.devtools/gha-deploy-service.bash starlet"
      - name: "Deploy tgfeed"
        run: "./.devtools/gha-deploy-service.bash tgfeed"
