name: 'Deploy'
on:
  workflow_run:
    workflows: ['Test']
    branches: ['master']
    types:
      - 'completed'
permissions:
  id-token: 'write'
  contents: 'read'
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v6'
        with:
          # Show Git tags in version.
          fetch-depth: 0
      - name: 'Set up Go'
        uses: 'actions/setup-go@v6'
        with:
          go-version-file: 'go.mod'
      - name: 'Deploy starlet'
        run: "./.devtools/gha-deploy-service.bash starlet"
      - name: "Deploy tgfeed"
        run: "./.devtools/gha-deploy-service.bash tgfeed"
