name: 'Test'
on:
  push:
    branches: ['master']
  pull_request:
jobs:
  test:
    name: 'Test'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v4'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go.mod'
      - name: 'Set up ruff'
        run: 'pip install ruff'
      - name: 'Test'
        run: 'go tool pre-commit'
      - name: 'Trigger vanity deploy'
        if: "github.ref == 'refs/heads/master'"
        env:
          VANITY_DEPLOY_HOOK: '${{ secrets.VANITY_DEPLOY_HOOK }}'
        run: |
          curl "$VANITY_DEPLOY_HOOK"
